### ISSUE TITLE
Action not found

### ISSUE THREAD

**Issue by kakadiadarpan** [blombard/review-reminder#12]
Hey @blombard! Thanks for making this action, I tried using it but got the below error 😓 

![Screenshot 2021-08-13 at 10 40 34](https://user-images.githubusercontent.com/10805593/129329910-590d306a-4d9c-4741-93d9-e5b63c7670f7.png)

Configuration:
```yml
on:
    schedule:
        - cron: '*/30 * * * 1-5'
        # At every 30th minute on every day-of-week from Monday through Friday.

jobs:
    deploy:
        name: Review reminders
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: blombard/review-reminder@master
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  reminder-comment: '🏓 please review this PR.'
                  days-before-reminder: '1'

```

Am I doing something wrong here? 🤔
